[theme]
primaryColor = "#FBBD1E"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#323438"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[client]
toolbarMode = "minimal"
